CREATE TABLE IF NOT EXISTS `#__easyquickicons` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `asset_id` int(10) unsigned NOT NULL DEFAULT '0',
  `name` varchar(255) NOT NULL,
  `component` varchar(255) NOT NULL,
  `link` varchar(255) NOT NULL,
  `target` varchar(8) NOT NULL,
  `published` tinyint(3) NOT NULL,
  `catid` int(11) NOT NULL,
  `ordering` int(11) NOT NULL,
  `custom_icon` tinyint(3) NOT NULL,
  `icon` varchar(255) NOT NULL,
  `icon_path` varchar(255) NOT NULL,
  `access` int(10) NOT NULL,
  `description` varchar(255) NOT NULL,
  `created_by` int(10) unsigned NOT NULL,
  `created_by_alias` varchar(255) NOT NULL,
  `created_date` datetime NOT NULL,
  `modified_date` datetime NOT NULL,
  `checked_out` int(10) NOT NULL,
  `checked_out_time` datetime NOT NULL,
  `publish_up` datetime NOT NULL,
  `publish_down` datetime NOT NULL,
  `language` char(7) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;